# Generated by Django 4.2.4 on 2023-08-03 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("is_complete", "-created_at")},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="completed",
            new_name="is_complete",
        ),
    ]
